#!/usr/bin/env python3
"""Offline evidence and inactive BUILD02 package generation; no traffic process."""
from pathlib import Path
import json,hashlib,difflib,datetime
ROOT=Path('/Users/yuhongzhang/Desktop/Masterarbeit-Ramp-Metering');B=ROOT/'artifacts/stage6_recovery_p2_revision_01/engineering';D=B/'build_recovery_diagnosis_revision01'
def bind(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def put(n,v):
 with (D/n).open('x') as f:json.dump(v,f,indent=2,sort_keys=True);f.write('\n')
oldcard=json.loads((B/'SG6_BUILD_request_card_revision03.json').read_text());receipt=json.loads((B/'build_attempts/BUILD01/build_receipt.json').read_text());started=json.loads((B/'build_attempts/BUILD01/started.json').read_text())
assert bind(B/'SG6_BUILD_request_card_revision03.json')['sha256']=='33ee32943e8420a38514bd67d372204c7f019569187ed95202c8daf4961095bd'
log=json.loads((D/'scoped_system_log_unsandboxed.json').read_text());matched=[x for x in log if 'netconvert(21722)' in x.get('eventMessage','')];assert len(matched)==1
entry=matched[0];parsed=datetime.datetime.fromisoformat(entry['timestamp']);lag=parsed.timestamp()-started['wallclock_started']
for f in oldcard['inputs']:assert bind(Path(f['path']))==f
put('diagnostic_findings.json',{
 'status':'READONLY_DIAGNOSIS_COMPLETE_ROOT_CAUSE_UNCONFIRMED','current_new_netconvert_starts':0,
 'context':{'AGENTS':'reviewed','phase':'P2 stopped BUILD01; newer user instruction authorizes evidence-driven recovery','formal_protocol':'empty; no formal runs','scientific_values':'unchanged Proposed P1 Candidate B','user_instruction':'排查原因，尝试直到成功','delegated_boundary':'diagnosis/package only; no new netconvert until independent review'},
 'confirmed':{'BUILD01_pid':started['pid'],'started_utc':datetime.datetime.fromtimestamp(started['wallclock_started'],datetime.timezone.utc).isoformat(),'returncode':receipt['returncode'],'wallclock_s':receipt['wallclock_s'],'no_stdout_stderr':True,'no_network_file':True,'sandbox_event':entry['eventMessage'],'event_time':entry['timestamp'],'seconds_after_started':lag,'binary_architecture':'arm64 Mach-O','direct_non_system_libraries_readable':7,'binary_xattrs':'none reported'},
 'root_cause':'Unknown. Sandbox denial is observed; causation of stall not established. No retained live stack/CPU/syscall record.',
 'hypotheses':[
 {'id':'H1','claim':'Sandbox interaction stalls native initialization','support':'PID/time-matched kern.bootargs denial','status':'testable, unconfirmed','next_discriminator':'BUILD02 supported require_escalated launch, same binary/input bytes; optional one live stack sample'},
 {'id':'H2','claim':'Input parsing/build computation waits or stalls','support':'No direct trace; static source/XSD checks passed but runtime untested','status':'unknown','next_discriminator':'verbose stage output and live sample if still running'},
 {'id':'H3','claim':'Transient loader/security/environment startup delay','support':'Native binary has7 direct framework libraries, no binary quarantine attribute','status':'unknown; existence of libraries is not successful dynamic loading','next_discriminator':'same next-attempt diagnostics; no arbitrary library/environment changes'}],
 'log_query':{'initial_sandbox_result':'log: Cannot run while sandboxed','supported_escalated_read_only_export_succeeded':True,'argv':['/usr/bin/log','show','--style','json','--start','2026-09-19 21:32:20','--end','2026-09-19 21:33:05','--predicate','processID == 21722 OR (eventMessage CONTAINS "netconvert")'],'window_local':'2026-09-19 21:32:20 to21:33:05 Europe/Berlin UTC+02:00','raw_export':bind(D/'scoped_system_log_unsandboxed.json')},
 'preserved_inputs':oldcard['inputs'],'source_input_bytes_changed':False,'runner_only_differences':['new attempt identity/claim/output','supported tool sandbox escalation','--output-file command-line override','--verbose true','optional bounded read-only startup stack sample'],
 'prohibited':['SUMO','TraCI','GUI','manual compiled edit','scientific network changes','repeat old BUILD01','blind retry'],
 'source_references':[{'url':'https://sumo.dlr.de/doxygen/da/d3e/_options_i_o_8cpp_source.html','claim':'Current official OptionsIO loads config then reparses CLI; not claimed exact installed binary source'},{'url':'https://eclipse.dev/sumo/docs/Basics/Using_the_Command_Line_Applications.html','claim':'Official configuration/command-line documentation'}],
 'confidence':{'process_and_matched_denial':'High','denial_caused_timeout':'Unknown','BUILD02_will_succeed':'Unknown'}})
(D/'build01_to_build02_executor.diff').write_text(''.join(difflib.unified_diff((B/'build01_executor.py').read_text().splitlines(True),(D/'build02_executor.py').read_text().splitlines(True),fromfile=str(B/'build01_executor.py'),tofile=str(D/'build02_executor.py'))))
put('recovery_budget_reconciliation.json',{'status':'reconciled_with_explicit_exclusions','previous_budget':bind(B/'budget_reconciliation_revision02.json'),'BUILD01_receipt':bind(B/'build_attempts/BUILD01/build_receipt.json'),'specified_scope_lower_bounds_now':{'SUMO':25,'netconvert':13,'TraCI':1,'GUI':'unknown'},'recovery_actual_tool_starts':{'netconvert':1,'SUMO':0,'TraCI':0,'GUI':0},'BUILD01_consumed_irrevocably':True,'new_card_limits':oldcard['proposed_limits'],'overall_recovery_governance':{'maximum_further_netconvert_attempts':3,'monitored_s_per_attempt':30,'aggregate_monitored_s':90,'observed_bytes_per_attempt':100000000,'aggregate_observed_bytes':300000000,'automatic_loop':False,'future_attempts_require_new_evidence_and_independent_review':True,'no_new_user_approval_needed_inside_explicit_current_authorization':True,'only_BUILD02_defined_now':True},'hard_caps_claimed':False,'no_historical_budget_transfer':True})
card=json.loads((D/'SG6_BUILD_request_card_draft.json').read_text());card['kind']='SG6_BUILD_REQUEST_FINAL_OFFLINE';card['status']='Proposed_internal_review_pending_under_continuing_user_authorization';card['approved']=False;card['authorized_starts']=0;card['launch_eligible']=False
card['execution_contract']={'executor':bind(D/'build02_executor.py'),'test_script':bind(D/'test_build02_executor.py'),'test_receipt':bind(D/'fake_process_tests_revision01/test_receipt.json'),'contract_document':bind(D/'BUILD02_EXECUTION_CONTRACT.md'),'watchdog_poll_s':0.05,'termination_grace_s':1,'kill_confirmation_wait_s':1,'automatic_retry':False,'old_attempt_reuse':False,'approval_sidecar_required':True,'sidecar_authority':'Parent creates only after scientific review under exact continuing user quote; do not claim user separately saw this later SHA'}
card['project_cumulative_budget']={'status':'reconciled_with_explicit_exclusions','evidence':bind(D/'recovery_budget_reconciliation.json'),'unused_historical_budget_transferred':False}
card['hypothesis']='H1 sandbox interaction; matched kern.bootargs denial is observed, causal role unconfirmed'
card['diagnostic_evidence']=bind(D/'diagnostic_findings.json');card['unchanged_source_invariant_receipt']=bind(B/'offline_verification_receipt_revision03.json');card['source_input_bytes_changed']=False;card['supersedes_for_execution']=None;card['previous_consumed_attempt']=bind(B/'BUILD01_failure_closeout.json');card['approved_predecessor_card_readonly']=bind(B/'SG6_BUILD_request_card_revision03.json')
card['monitoring_note']='30s monitored timeout and100MB observed stop line,50ms polling; not hard caps, maximum overshoot unbounded. Preserve failures and never retry same claim.'
card['executor_invocation']={'argv':[str(ROOT/'.venv/bin/python'),str(D/'build02_executor.py'),'--card',str(D/'BUILD02_request_card.json'),'--approval',str(D/'BUILD02_user_approval.json'),'--execute'],'cwd':str(ROOT),'SUMO_HOME':oldcard['environment_overrides']['SUMO_HOME'],'tool_sandbox_permissions':'require_escalated','tool_justification':'用户已授权排查并尝试至构建成功。仅运行经独立审查的 BUILD02 专用执行器，一次 netconvert，原输入和科学参数不变；用于检验已记录的 sandbox 拒绝与超时的关系。保留30秒/100MB监测线，不运行SUMO/TraCI/GUI。','status':'NOT_EXECUTED; independent review and derived sidecar pending'}
card['sample_observation']={'when':'at2s if exact recorded PID and process group still match the live netconvert','argv_template':['/usr/bin/sample','<BUILD02_started_pid>','1','1','-file',str(B/'build_attempts/BUILD02/startup.sample.txt')],'timeout_s':5,'max_invocations':1,'netconvert_starts':0,'if_already_exited':'skip','if_permission_denied':'record; no bypass','included_in_attempt_output_accounting':True}
card['preflight'].append('New continuing user authorization plus independent review; supported sandbox escalation approval is still required by tool')
put('BUILD02_request_card.json',card)
put('BUILD02_approval_TEMPLATE_NOT_APPROVED.json',{'status':'NOT_APPROVED','synthetic_test_only':False,'scope':'SG6-BUILD BUILD02 only','card_path':str(D/'BUILD02_request_card.json'),'card_sha256':bind(D/'BUILD02_request_card.json')['sha256'],'max_netconvert_starts':1,'monitoring_semantics':'polling_50ms_possible_overshoot_preserved','user_approval_quote':'排查原因，尝试直到成功','approved_at':None,'authority_mode':'continuing_user_instruction_with_independent_review','review_receipt':None,'note':'Parent may activate separate sidecar after independent review under continuing authorization; never edit old card or old sidecar.'})
print(json.dumps({'diagnosis':bind(D/'diagnostic_findings.json'),'BUILD02_card':bind(D/'BUILD02_request_card.json'),'wrapper':bind(D/'build02_executor.py'),'tests':bind(D/'fake_process_tests_revision01/test_receipt.json')},indent=2))
