import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const docker = '/opt/homebrew/bin/docker';
const context = ['--context', 'colima-memory-pilot'];
const image = 'sha256:9798254a8cc06276b7c5b3c19df49f136fae25d579564e1f01f9c4b9b8cd2d11';
const volume = 'tdai-ramp-metering-snapshot-20260909';
const content = readFileSync('docs/memory/project_snapshot_20260909.md', 'utf8');
const sha = createHash('sha256').update(content.trim()).digest('hex');
const run = (args, options = {}) => execFileSync(docker, [...context, ...args], { encoding: 'utf8', timeout: 60000, maxBuffer: 1024 * 1024, ...options });
const volumes = run(['volume', 'ls', '--format', '{{.Name}}']).trim().split('\n');
if (volumes.includes(volume)) throw Error('Target volume already exists; refusing overwrite');
run(['image', 'inspect', image]);
run(['volume', 'create', '--label', 'project=Masterarbeit-Ramp-Metering', volume]);
const payload = JSON.stringify({ content, config: readFileSync('scripts/memory/config.yaml', 'utf8'), script: readFileSync('scripts/memory/snapshot_probe.mjs', 'utf8').replaceAll('/app/project-snapshot.txt', '/tmp/project-snapshot.txt') });
const bootstrap = "const fs=require('fs');const p=JSON.parse(fs.readFileSync(0,'utf8'));fs.writeFileSync('/tmp/project-snapshot.txt',p.content);fs.writeFileSync('/tmp/config.yaml',p.config);fs.writeFileSync('/tmp/probe.mjs',p.script);require('child_process').execFileSync('node',['/tmp/probe.mjs'],{stdio:'inherit',env:{...process.env,PILOT_STAGE:'write',TDAI_GATEWAY_CONFIG:'/tmp/config.yaml'}});";
const output = run(['run', '--rm', '-i', '--pull=never', '--network', 'none', '--read-only', '--cap-drop', 'ALL', '--security-opt', 'no-new-privileges', '--tmpfs', '/tmp:rw,size=32m', '--mount', `type=volume,source=${volume},target=/data`, '--entrypoint', 'node', image, '-e', bootstrap], { input: payload });
writeFileSync('docs/memory/storage_receipt_20260909.json', JSON.stringify({ project: 'Masterarbeit-Ramp-Metering', volume, image, sha, output }, null, 2), { flag: 'wx' });
console.log(JSON.stringify({ volume, sha, receipt: 'docs/memory/storage_receipt_20260909.json' }));
