import json
from pathlib import Path
import runtime_executor as e
B=Path(__file__).resolve().parent;E=B.parent
manifest=json.loads((B/'runtime_input_manifest.json').read_text());env=json.loads((E/'environment_binding.json').read_text())
def write(name,data):e.durable(B/name,data)
gate={'schema_version':1,'required_check_ids':e.REQUIRED,'allowed_technical_status':['PASS','FAIL'],'allowed_physical_status':['suitable','complete_evidence_but_comparison_unsuitable_physical_event'],'mandatory_bindings':['card_sha256','attempt_id','execution_receipt_sha256','output_manifest_sha256','analysis_version_binding'],'progression_rule':'all exactly 12 checks PASS AND technical PASS AND physical suitable AND no output violation; previous gates smoke then R0 required','checks':{'source_binding_exact':'all card/input/output identities and hashes exact','execution_complete_2700':'zero process exit; complete full window; no engine Error; all raw evidence retained','output_role_set_17_exact':'9 E1 + 2 E2 + FCD/queues/summary/tripinfo/vehroute/TLS, each required file exactly once','xml_roots_and_timegrids':'parse all XML; FCD/TLS/summary/queue labels0..2699; detectors90 consecutive30s intervals0..2700; no required frame gaps','planned_identity_coverage':'M1333,U150,X75,R300 or0; tripinfo all planned IDs exactly once including depart<0 never-inserted; no unknown IDs','departed_route_and_fcd_consistency':'vehroute covers departed; never-inserted may absent; times/routes/FCD consistent; unfinished explicitly sourced','population_conservation':'planned=never_inserted+departed; departed=arrived+in_network; integer residual0; physical events separate','actual_lane_and_connection_consistency':'actual lanes/route and compiled reachable lane chains; do not require every internal at1Hz; aux0 skip alone is limitation','detector_output_contract':'all fixed IDs/roles period30/positions; no detector loading error; real output not claim TraCI loaded coverage','tls_state_contract':'complete TLS states match registered cycle45Gr/3yr/9rG/3ry offset0 and lane links','output_manifest_complete':'verify all actual raw output hashes; no partial/extra unexplained XML; logs reviewed; live writer absent; exact final bytes','m_insertion_contract':'actual M first insertion main_up lane0/1 pos100±0.02, full primary domain main_up1200→main_down200'},'observations_separate':['R route inference versus observed lane changes','R passage absence itself not technical failure','M/U effect sign not acceptance gate','emergency_braking_count','first_R_aux0_1Hz_coverage_limit'],'no_new_user_prompt_between_passed_stages':True}
write('gate_contract.json',gate)
resource={'status':'Proposed_operational_ceiling_under_current_three_start_authorization','limits':e.LIMITS,'monitoring_semantics':'polling_50ms_possible_overshoot_preserved','maximum_overshoot_bytes':'unknown; not hard quota','historical_estimate_source':e.binding(E/'candidate_resource_estimate.json'),'derivation':{'max_population':1858,'labels':2700,'records_overestimate':5016600,'bytes_per_record_planning':256,'FCD_planning_bytes':1284249600,'remaining_other_output_bytes':215750400,'historical_samples':343495,'historical_s':3.7455701250000857,'rough_scaled_s':5016600/343495*3.7455701250000857,'timeout_s':180,'scope_total_s':540},'current_recovery_actual_before_this_package':{'SUMO':0,'netconvert':2,'TraCI':0,'GUI':0},'historical_count_note':'not a complete project lifetime total; no transfer of old six-start budget'}
write('resource_budget.json',resource)
card={'kind':'P2_THREE_START_RUNTIME_CARD','approved':False,'status':'ready_for_independent_static_review_not_yet_launchable','scope':'P2 smoke then seed17 R0/R720 only','limits':e.LIMITS,'attempts':manifest['attempts'],'binary':env['binary']['sumo'],'network':e.binding(E/'build_attempts/BUILD02/network.net.xml'),'executor':e.binding(B/'runtime_executor.py'),'test_receipt':e.binding(B/'executor_test_receipt.json'),'static_receipt':e.binding(B/'static_validation_receipt_revision02.json'),'contract':e.binding(B/'RUNTIME_CONTRACT.md'),'gate_contract':e.binding(B/'gate_contract.json'),'input_manifest':e.binding(B/'runtime_input_manifest.json'),'resource_budget':e.binding(B/'resource_budget.json'),'schema_bindings':env['schema_files'],'compiled_acceptance':e.binding(E/'build02_compiled_review_revision02/engineering_closeout.json'),'environment':{'SUMO_HOME':e.SUMO_HOME,'PATH':'/usr/bin:/bin','LANG':'C','LC_ALL':'C','HOME':'inherit current user HOME','forbid_environment_prefixes':['DYLD_','LD_']},'cwd':str(e.ROOT),'approval_sidecar_path':str(B/'RUNTIME_user_approval.json'),'gate_path_pattern':str(B/'gates/<attempt_id>.json'),'monitoring_semantics':'polling_50ms_possible_overshoot_preserved','scientific_scope':'single-seed descriptive mechanism diagnosis; no complete P1 two-seed acceptance','structural_failure':'stop sequence on incorrect topology/loaded detector/TLS/actual insertion/invalid route/physical collision or teleport; preserve evidence; do not change/retry','execution_tool':{'sandbox_permissions':'require_escalated','justification':'Execute the user-authorized bounded SUMO technical smoke / seed17 diagnostic attempt using the reviewed immutable card, independent output directory and fail-closed no-retry executor.'}}
card['wrapper_argv_by_attempt']={a['attempt_id']:[str(e.ROOT/'.venv/bin/python'),str(B/'runtime_executor.py'),'--card',str(B/'RUNTIME_VALIDATION_CARD.json'),'--approval',str(B/'RUNTIME_user_approval.json'),'--attempt',a['attempt_id'],'--execute'] for a in card['attempts']}
write('RUNTIME_VALIDATION_CARD.json',card)
write('RUNTIME_user_approval.template.json',{'status':'inactive_template','card_path':str(B/'RUNTIME_VALIDATION_CARD.json'),'card_sha256':e.digest(B/'RUNTIME_VALIDATION_CARD.json'),'scope':card['scope'],'max_SUMO_starts':3,'synthetic_test_only':False,'monitoring_semantics':card['monitoring_semantics'],'user_approval_quote':'PRIMARY_RECORD_EXACT_EXISTING_USER_AUTHORIZATION','review_receipt':None,'provenance_note':'user authorized the continuous bounded workflow; primary binds this later final card after review; no claim user personally approved a later SHA'})
files=[e.binding(p) for p in sorted(B.rglob('*')) if p.is_file() and '__pycache__' not in p.parts]
write('runtime_delivery_manifest.json',{'status':'ready_for_independent_static_review','real_SUMO_starts':0,'real_netconvert_starts':0,'files':files,'card_sha256':e.digest(B/'RUNTIME_VALIDATION_CARD.json'),'known_initial_validator_error':'original73-check receipt has3falsefail due wrong roles JSON key; revision02 corrects validator only;9XMLXSD passed both; no traffic input edits','confidence':'High for file/static/test evidence; runtime behavior not yet evaluated'})
print(json.dumps({'card':e.binding(B/'RUNTIME_VALIDATION_CARD.json'),'manifest':e.binding(B/'runtime_delivery_manifest.json')},indent=2))
