"""Summarize completed bounded execution receipts; no simulation or data modification."""
from pathlib import Path
import hashlib,json,statistics,shutil
root=Path.cwd();b=root/'artifacts/formal_development_20261007_v1';e=b/'engineering';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
rows=[]
for p in sorted((b/'receipts').glob('*.json')):
 r=json.loads(p.read_text());raw=root/'data/raw/formal_development_20261007_v1'/r['run_id']/'outputs';physical='sumo.log' in r['output_manifest']
 role='FIX02_CONTROL' if r['run_id'].endswith('A03') and r['treatment'] in ('T1','T2') else ('OPEN_NEUTRALITY_BASELINE' if r['status']=='COMPLETED' and r['treatment']=='OPEN' else 'PRESERVED_TECHNICAL_OR_DIAGNOSTIC')
 rows.append({'run_id':r['run_id'],'status':r['status'],'role':role,'worker_attempt':True,'physical_SUMO_evidence':physical,'wall_s':r['wall_s'],'payload_bytes':r['output_bytes'],'actual_raw_bytes':sum(x.stat().st_size for x in raw.rglob('*') if x.is_file()),'receipt':str(p.relative_to(root)),'receipt_sha256':sha(p),'return_code':r['return_code'],'stop_reason':r['stop_reason']})
controls=[x for x in rows if x['role']=='FIX02_CONTROL'];assert len(controls)==12 and all(x['status']=='COMPLETED' for x in controls)
gates={}
for row in controls:
 parts=row['run_id'].split('_');ramp=parts[2];seed=parts[3];treatment=parts[4];g=root/'data/processed/formal_development_20261007_v1'/f'FIX02_{treatment}_{ramp}_{seed}_A03/FIX02_DATA_GATE.json';v=json.loads(g.read_text());assert v['data_layer']=='PASS' and v['safety_and_rule_replay']=='PASS_OBSERVED_RUN';gates[row['run_id']]={'path':str(g.relative_to(root)),'sha256':sha(g),'data_layer':v['data_layer'],'safety_and_rule_replay':v['safety_and_rule_replay'],'rate_capability':v['rate_capability']}
card=json.loads((b/'inputs/DEV_M3600_R750_S17_T1_A03/card.json').read_text());assert all(sha(Path(p))==h for p,h in card['source_sha256'].items());assert sha(e/'PARAMETER_CONTRACT.json')==card['contract_sha256'];assert sha(e/'FIX02_REPAIR_ADDENDUM.json')==card['repair_addendum_sha256']
wall=[r['wall_s'] for r in controls];sizes=[r['payload_bytes'] for r in controls]
value={'classification':'DEVELOPMENT_EXECUTION_LEDGER','status':'ALL_12_FIX02_CONTROLS_COMPLETED_WITH_PERSISTED_DATA_GATES','rows':rows,'worker_attempts':len(rows),'physical_SUMO_starts':sum(r['physical_SUMO_evidence'] for r in rows),'completed_new_runs':sum(r['status']=='COMPLETED' for r in rows),'failed_attempts':sum(r['status']!='COMPLETED' for r in rows),'corrected_control_combinations':len(controls),'accepted_OPEN_baseline_slots':6,'corrected_coverage_slots':18,'all_attempts_wall_s':sum(r['wall_s'] for r in rows),'all_attempts_payload_bytes':sum(r['payload_bytes'] for r in rows),'actual_raw_directory_bytes':sum(r['actual_raw_bytes'] for r in rows),'free_disk_bytes':shutil.disk_usage(root).free,'fixed_limits':card['resources'],'control_resource_summary':{'wall_min_s':min(wall),'wall_max_s':max(wall),'wall_median_s':statistics.median(wall),'wall_mean_s':statistics.mean(wall),'total_wall_s':sum(wall),'payload_min_bytes':min(sizes),'payload_max_bytes':max(sizes),'payload_mean_bytes':statistics.mean(sizes),'total_payload_bytes':sum(sizes)},'source_sha256':card['source_sha256'],'contract_sha256':card['contract_sha256'],'repair_addendum_sha256':card['repair_addendum_sha256'],'independent_data_gates':gates,'warnings':['TraCI API UserWarning retained in completed workers; no suppression.','Offline completion-summary parser initially included trailing punctuation in4200.00.; report-only correction applied, no run/source/card changed or repeated.'],'limitations':['Mechanical completion and observed safety do not qualify commanded service.','Six OPEN slots are accepted reuse per science and data; one new neutral OPEN substitutes the S17 R900 baseline and is not a seventh baseline combination.','Old controls/failed attempts remain separate; no formal inference.'],'next_action':'No further simulations; independent final synthesis/scientific closeout and parent governance updates.'}
with (e/'FINAL_EXECUTION_LEDGER.json').open('x') as f:json.dump(value,f,indent=2);f.write('\n')
print(json.dumps({k:value[k] for k in ('worker_attempts','physical_SUMO_starts','completed_new_runs','failed_attempts','corrected_coverage_slots','actual_raw_directory_bytes','control_resource_summary')}))
