#!/usr/bin/env python3
"""Finalize static immutable package; does not spawn simulations."""
import hashlib,json,sys
from pathlib import Path
B=Path(__file__).absolute().parent;R=B.parents[2]
H=Path('/Library/Frameworks/EclipseSUMO.framework/Versions/1.26.0/EclipseSUMO/share/sumo');OLD=R/'artifacts/stage6_targeted_validation_20260920_v1/engineering'
RUN=R/'data/raw/stage6_o2_causal_diagnostic_20260921_v1/O2_C_S17_450_attempt1'
def bind(p):p=Path(p);return {'path':str(p),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def write(p,v):
 with p.open('x') as f:json.dump(v,f,indent=2,sort_keys=True);f.write('\n')
write(B/'authorization_provenance.json',{'status':'conditional_user_authorization_package_only_pending_exact_static_review','source':'current user instruction in this task','user_exact_quote':'只有现有数据确实不足以区分上述机制时，才提出并执行最小必要的新 instrumentation / validation run。','condition_evaluation':'Parent and scientific reviewer report existing C lacks selected leader/blocking reason; minimum single C seed17 end450 instrumentation is within this conditional instruction. This file records provenance, not a claim the user saw the later card SHA.','evidence':{'fcd':bind(R/'data/raw/stage6_targeted_validation_20260920_v1/TV_C_S17_attempt1/outputs/fcd.xml'),'missing_fields':['leaderID','leaderGap','leaderSpeed','selected_blocking_cause'],'observed_vehicle_fields':['angle','id','lane','pos','slope','speed','type','x','y'],'scope_of_absence':'Archived FCD has no such selected leader fields; native LC and existing frame evidence do not identify actual U35/R70 blocking cause.'},'scope':'one C seed17 reproduction, 0-450s, original behavior inputs, native leader plus read-only TraCI, no setters, no retry, no further start','requires_before_launch':'Parent exact final scientific/static review and bound release sidecar; no further user confirmation for this approved scope.'})
checks=['exact_input_and_binary_bindings','one_start_and_process_group_terminated','execution_clock_0_to_450','eighteen_XML_roles_complete','observer_steps_and_target_window_complete','native_leader_and_actual_vehicle_geometry_fields','archived_C_common_prefix_neutrality','TraCI_to_FCD_position_and_clock_alignment','original_program_and_detector_contract','physical_events_and_engineering_errors','cutoff450_population_and_censoring','output_manifest_and_exact_final_bytes']
write(B/'diagnostic_gate_contract.json',{'status':'PROPOSED_STATIC_GATE_CONTRACT','required_checks':checks,'allowed_status':['PASS','FAIL','INDETERMINATE','NOT_RUN'],'all_required_for_diagnostic_interpretation':'PASS','no_followup_start_under_any_outcome':True,'prefix_comparison':{'FCD':'All original fields including id/lane/pos/speed/XY/type/angle/slope and row order per label0..449 equal archived C exactly at original precision; additional leader fields excluded ONLY from neutrality comparison. No tolerance added to original XML strings.','other_timebounded_roles':'Compare all 11 detector roles for intervals ending<=450, queue/summary/TLS labels<450, native lanechange event times<450, semantic content/order. Ignore XML comments/whitespace and summary step duration (wall-clock computation) only.','horizon_dependent_roles':['tripinfo.xml','vehroute.xml'],'horizon_dependent_requirement':'Do not compare completed2700 summaries against cutoff450. Reconcile departed/arrived/active IDs and explicitly separate not-yet-scheduled beyond450 from pending insertion before450; preserve complete original planned demand as context.'},'observer_alignment':'Compare recorded step_before/after with native FCD same IDs/fields. Expect candidate before label, but require observed agreement; inspect0/1/2 and every385..430. Raw query precision higher than FCD; compare after original2-decimal rounding with documented floating representation tolerance only. TLS query timing is separate; do not force equality at phase transitions without step semantics.','body_occupancy':'Use actual queried length, route history, lane length and front position to identify vehicle rear occupying preceding shared lane. Never infer same-path empty gap merely by excluding a vehicle whose front entered the other internal branch. This geometry alone is not a native selected-blocker label.','physical':'Any collision/teleport stops and preserves partial evidence. Data found only after completion makes complete evidence unsuitable. Query failure/unknown alignment/neutrality prevents causal use.','O2_decision':'Not automatically resolved by technical PASS; independent scientific review required; strict registered storage-cross rules unchanged.'})
py=Path(sys.executable).resolve();sumo=H.parent.parent/'bin/sumo' # overwritten explicitly below
sumo=Path('/Library/Frameworks/EclipseSUMO.framework/Versions/1.26.0/EclipseSUMO/bin/sumo')
net=OLD/'build_attempts/TV_BUILD01/network.net.xml'
static=json.loads((B/'static_validation_receipt.json').read_text());sources=json.loads((B/'references/source_bindings.json').read_text())['sources']
# Bind installed Python client dependency files as well as specific interface sources.
deps=[p for directory in [H/'tools/traci',H/'tools/sumolib'] for p in directory.rglob('*.py') if p.is_file()]
inputs=[bind(p) for p in sorted((B/'inputs').iterdir())]
write(B/'input_manifest.json',{'status':'STATIC_BOUND_NOT_RUN','attempt_id':'O2_C_S17_450_attempt1','run_root':str(RUN),'output_root':str(RUN/'outputs'),'inputs':inputs,'network':bind(net),'original_counts':{'M':1333,'R':300,'U':150,'X':75},'counts_scope':'original0-1500 schedule; cannot call all scheduled-by450','begin':0,'end':450,'step':1,'seed':17,'program':'C_STRONG','geometry_and_behavior_change':False})
limits={'SUMO_starts':1,'TraCI_connections':1,'netconvert':0,'GUI':0,'retry':0,'per_attempt_monitored_s':180,'total_monitored_s':180,'per_attempt_observed_bytes':200000000,'total_observed_bytes':200000000}
files=[p for p in B.rglob('*') if p.is_file() and '/tests/fixtures_' not in str(p)]
rows=[bind(p) for p in files]+sources+static['schema_bindings']+[bind(p) for p in deps]+[bind(py),bind(sumo),bind(net),bind(Path('/usr/sbin/lsof'))]
bindings=list({r['path']:r for r in rows}.values())
card={'kind':'O2_SINGLE_START_DIAGNOSTIC','approved':False,'status':'STATIC_PACKAGE_PENDING_EXACT_REVIEW_NO_LAUNCH','purpose':'technical instrumentation of C U35/R70 event, not science replication','limits':limits,'budget_semantics':'180s and200MB observed stop-lines,50ms polling, possible overshoot; existing TV 5/5 remains exhausted separately','previous_task':{'card':bind(OLD/'RUNTIME_CARD.json'),'consumed_SUMO_starts':5,'wallclock_s':7.03850783398957,'final_bytes':170383856,'transferred_budget':0},'SUMO_HOME':str(H),'cwd':str(R),'environment':{'SUMO_HOME':str(H),'PATH':'/usr/bin:/bin','LANG':'C','LC_ALL':'C','HOME':'inherit_only','PYTHON_and_loader_injection':'rejected'},'python':bind(py),'sumo_binary':bind(sumo),'sumo_version':'1.26.0 evidenced by archived C log and bound binary, re-read over same TraCI connection','network':bind(net),'executor':bind(B/'runtime_executor.py'),'observer':bind(B/'observer.py'),'static_receipt':bind(B/'static_validation_receipt.json'),'test_receipt':bind(B/'offline_test_receipt_revision02.json'),'input_manifest':bind(B/'input_manifest.json'),'user_authorization_binding':bind(B/'authorization_provenance.json'),'approval_path':str(B/'O2_RELEASE_APPROVAL.json'),'review_expected':{'status':'PASS_STATIC_FINAL','stage':'exact_o2_diagnostic_package','card_sha256':'must equal this final card; no circular embedded hash'},'attempt':{'attempt_id':'O2_C_S17_450_attempt1','run_root':str(RUN),'output_root':str(RUN/'outputs'),'argv':[str(py),'-B',str(B/'observer.py'),'--card',str(B/'O2_DIAGNOSTIC_CARD.json')]},'sumo_argv':[str(sumo),'-c',str(B/'inputs/scenario.sumocfg'),'--remote-port','8819','--num-clients','1'],'bindings':bindings}
write(B/'O2_DIAGNOSTIC_CARD.json',card)
write(B/'O2_RELEASE_APPROVAL.template.json',{'status':'TEMPLATE_NOT_RELEASED','card_sha256':bind(B/'O2_DIAGNOSTIC_CARD.json')['sha256'],'max_SUMO_starts':1,'scope':'single_C_seed17_end450_readonly_diagnostic','user_authorization_binding':card['user_authorization_binding'],'review_receipt':None,'release_rule':'Parent writes separate O2_RELEASE_APPROVAL.json only after exact review PASS, status conditionally_authorized_released_after_exact_review. Existing user instruction, not later personal approval of this SHA.'})
print(json.dumps({'card':bind(B/'O2_DIAGNOSTIC_CARD.json'),'binding_count':len(bindings),'python':str(py)}))
