import json
from pathlib import Path
import runtime_executor as e
B=Path(__file__).resolve().parent;O=B.with_name('runtime_validation_revision01')
def write(name,data):e.durable(B/name,data)
old=json.loads((O/'RUNTIME_VALIDATION_CARD.json').read_text());rows=json.loads((O/'runtime_delivery_manifest.json').read_text())['files']
for r in rows:e.verify(r)
checks=[{'check_id':'revision01_all_delivery_bindings_unchanged','status':'PASS','file_count':len(rows)},{'check_id':'revision01_static_inputs_and_XSD_pass','status':'PASS','evidence':e.binding(O/'static_validation_receipt_revision02.json')},{'check_id':'revision02_fake_tests_pass','status':'PASS','evidence':e.binding(B/'executor_test_receipt.json')},{'check_id':'all_registered_run_roots_still_absent','status':'PASS' if all(not Path(a['run_root']).exists() for a in old['attempts']) else 'FAIL'}]
write('static_validation_receipt.json',{'status':'PASS' if all(c['status']=='PASS' for c in checks) else 'FAIL','checks':checks,'retained_input_checks':73,'retained_XML_XSD_checks':9,'real_SUMO_starts':0,'real_netconvert_starts':0,'revision_change':'executor review enforcement and operator physical-stop contract only; no science/input bytes changed'})
g=json.loads((O/'gate_contract.json').read_text());g['runtime_physical_event']='operator-observed collision/teleport while live: immediately stop; partial_evidence_physical; any later stage blocked';g['after_completion_physical_event']='first discovered afterward: complete_evidence_but_comparison_unsuitable_physical_event; later stage blocked';write('gate_contract.json',g)
card=dict(old);card['revision']=2;card['supersedes_card']=e.binding(O/'RUNTIME_VALIDATION_CARD.json');card['executor']=e.binding(B/'runtime_executor.py');card['contract']=e.binding(B/'RUNTIME_CONTRACT.md');card['test_receipt']=e.binding(B/'executor_test_receipt.json');card['static_receipt']=e.binding(B/'static_validation_receipt.json');card['gate_contract']=e.binding(B/'gate_contract.json');card['approval_sidecar_path']=str(B/'RUNTIME_user_approval.json');card['review_receipt_requirements']={'status':'PASS_STATIC_FINAL','stage':'exact_runtime_package','card_sha256':'must equal this card SHA256'};card['physical_stop_request']={'path_pattern':str(e.BASE/'runs/<attempt_id>/physical_stop_request.json'),'writer':'primary after clearly observed actual event while live','required_fields':{'event_type':'collision OR teleport','observer':'primary','observed_excerpt':'exact actual event evidence','source_path':'log or observed event source','observed_unix':'timestamp'},'effect':'terminate process group; partial_evidence_physical; no retry/following attempt','observation_limit':'operator log cadence and buffering; no continuous-event-sensing claim'}
card['wrapper_argv_by_attempt']={a['attempt_id']:[str(e.ROOT/'.venv/bin/python'),str(B/'runtime_executor.py'),'--card',str(B/'RUNTIME_VALIDATION_CARD.json'),'--approval',str(B/'RUNTIME_user_approval.json'),'--attempt',a['attempt_id'],'--execute'] for a in card['attempts']}
write('RUNTIME_VALIDATION_CARD.json',card)
approval=json.loads((O/'RUNTIME_user_approval.template.json').read_text());approval['card_path']=str(B/'RUNTIME_VALIDATION_CARD.json');approval['card_sha256']=e.digest(B/'RUNTIME_VALIDATION_CARD.json');write('RUNTIME_user_approval.template.json',approval)
files=[e.binding(p) for p in sorted(B.rglob('*')) if p.is_file() and '__pycache__' not in p.parts]
write('runtime_delivery_manifest.json',{'status':'ready_for_exact_static_review','files':files,'retained_input_manifest':old['input_manifest'],'previous_delivery_manifest':e.binding(O/'runtime_delivery_manifest.json'),'real_SUMO_starts':0,'real_netconvert_starts':0,'card_sha256':e.digest(B/'RUNTIME_VALIDATION_CARD.json'),'scope':'three starts total over retained run directories; revision02 does not add another three'})
print(json.dumps({'card':e.binding(B/'RUNTIME_VALIDATION_CARD.json'),'manifest':e.binding(B/'runtime_delivery_manifest.json')},indent=2))
