import json
from pathlib import Path
import runtime_executor as e
B=Path(__file__).resolve().parent;O=B.with_name('runtime_validation_revision03');m=json.loads((B/'runtime_input_manifest.json').read_text());old=json.loads((O/'RUNTIME_VALIDATION_CARD.json').read_text());h=json.loads((B/'prior_attempt_ledger.json').read_text())
def write(n,x):e.durable(B/n,x)
g=json.loads(Path(old['gate_contract']['path']).read_text());write('gate_contract.json',g)
resource={'status':'Proposed_operational_ceiling_under_continuing_bounded_smoke_troubleshooting_authorization','limits':e.LIMITS,'prior_consumption':e.binding(B/'prior_attempt_ledger.json'),'prior_starts':2,'new_starts_max':3,'cumulative_starts_max':5,'explicit_start_ceiling_change':'one above revision03 ceiling4; exactly one new technical smoke retry, conditional seed17 pair, no automatic repeats','prior_time_decimal_s':'22.032722626005124','prior_bytes':52751,'cumulative_time_s':549.3738820840008,'cumulative_bytes':4500023552,'remaining_time_decimal_s':'527.341159457995676','remaining_bytes':4499970801,'per_attempt_time_stop_s':180,'per_attempt_byte_stop':1500000000,'effective_attempt_allowance':'smaller of per-attempt ceiling and remaining cumulative envelope','monitoring_semantics':'polling_50ms_possible_overshoot_preserved','maximum_overshoot':'unknown; not hard quota','original_estimation_basis':old['resource_budget'],'no_reset':True};write('resource_budget.json',resource)
card=dict(old);card.update(revision=4,attempts=m['attempts'],limits=e.LIMITS,executor=e.binding(B/'runtime_executor.py'),contract=e.binding(B/'RUNTIME_CONTRACT.md'),test_receipt=e.binding(B/'executor_test_receipt.json'),static_receipt=e.binding(B/'static_validation_receipt.json'),gate_contract=e.binding(B/'gate_contract.json'),input_manifest=e.binding(B/'runtime_input_manifest.json'),resource_budget=e.binding(B/'resource_budget.json'),prior_attempt_ledger=e.binding(B/'prior_attempt_ledger.json'),approval_sidecar_path=str(B/'RUNTIME_user_approval.json'),supersedes_card=e.binding(O/'RUNTIME_VALIDATION_CARD.json'),gate_path_pattern=str(B/'gates/<attempt_id>.json'))
card['detector_repair_semantics']=e.binding(B/'evidence/OPTIONAL_FILTER_SEMANTICS.md');card['cumulative_runtime_budget']={'prior_starts':2,'new_max_starts':3,'maximum_including_failed_smokes':5,'explicit_change_from_revision03':'+1 cumulative start, under continuing technical smoke troubleshooting authorization','past_time_decimal_s':'22.032722626005124','past_bytes':52751,'cumulative_time_stop_s':549.3738820840008,'cumulative_byte_stop':4500023552,'remaining_time_decimal_s':'527.341159457995676','remaining_bytes':4499970801,'no_automatic_retry':True};card['physical_stop_request']['path_pattern']=str(B/'runs/<attempt_id>/physical_stop_request.json');card['structural_failure']='Any recognized structural/physical event immediately terminates current run and stops the entire card; any technical failure/nonzero also stops whole card; no edit-and-retry under this card.'
card['wrapper_argv_by_attempt']={a['attempt_id']:[str(e.ROOT/'.venv/bin/python'),str(B/'runtime_executor.py'),'--card',str(B/'RUNTIME_VALIDATION_CARD.json'),'--approval',str(B/'RUNTIME_user_approval.json'),'--attempt',a['attempt_id'],'--execute'] for a in card['attempts']}
write('RUNTIME_VALIDATION_CARD.json',card)
a=json.loads((O/'RUNTIME_user_approval.template.json').read_text());a.update(card_path=str(B/'RUNTIME_VALIDATION_CARD.json'),card_sha256=e.digest(B/'RUNTIME_VALIDATION_CARD.json'),user_approval_quote='smoke排查原因然后继续尝试',prior_consumed_SUMO_starts=2,cumulative_SUMO_starts_ceiling=5,explicit_ceiling_change='5 is one above revision03 ceiling4; original cumulative time/byte stop lines unchanged',provenance_note='Standing user authorization covers evidence-based technical smoke troubleshooting; primary may bind this exact final card only after independent review. The later card hash is not represented as personally reviewed by the user. No current approval is conferred by this inactive template.');write('RUNTIME_user_approval.template.json',a)
write('runtime_delivery_manifest.json',{'status':'ready_for_exact_static_review_not_authorized_by_template','files':[e.binding(p) for p in sorted(B.rglob('*')) if p.is_file() and '__pycache__' not in p.parts],'prior_runtime_delivery_manifest':e.binding(O/'runtime_delivery_manifest.json'),'prior_attempt_ledger':e.binding(B/'prior_attempt_ledger.json'),'card_sha256':e.digest(B/'RUNTIME_VALIDATION_CARD.json'),'real_SUMO_starts_this_packaging':0,'real_netconvert_starts_this_packaging':0,'prior_runtime_SUMO_starts':2,'new_scope_SUMO_max':3,'cumulative_ceiling5_explicit':True,'unchanged_time_bytes_ceiling':True})
print(json.dumps({'card':e.binding(B/'RUNTIME_VALIDATION_CARD.json'),'manifest':e.binding(B/'runtime_delivery_manifest.json'),'static':e.binding(B/'static_validation_receipt.json'),'tests':e.binding(B/'executor_test_receipt.json')},indent=2))
