"""Create machine-readable disabled build/launch request cards, never execute them."""
from pathlib import Path
import hashlib,json
OUT=Path(__file__).resolve().parent;ROOT=OUT.parents[2]
def bind(p):return {'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
def save(n,x):
    with (OUT/n).open('x') as f:json.dump(x,f,indent=2,sort_keys=True);f.write('\n')
m=json.loads((OUT/'input_manifest_revision03.json').read_text());env=json.loads((OUT/'environment_binding.json').read_text())
netcfg=OUT/'network_inputs/candidate.schema_revision02.netccfg';builddir=OUT/'build_attempts/BUILD01'
build={'schema_version':1,'kind':'SG6_BUILD_REQUEST_DRAFT','status':'Proposed_requires_user_approval','launch_eligible':False,'approved':False,'authorized_starts':0,'attempt_id':'BUILD01','binary':env['binary']['netconvert'],'argv':[env['binary']['netconvert']['path'],'-c',str(netcfg)],'cwd':str(ROOT),'environment_overrides':{'SUMO_HOME':env['SUMO_HOME']},'inputs':m['network_inputs'],'schema_bindings':env['schema_files'],'output_dir':str(builddir),'network_output':str(builddir/'network.net.xml'),'stdout_path':str(builddir/'netconvert.stdout.log'),'stderr_path':str(builddir/'netconvert.stderr.log'),'receipt_path':str(builddir/'build_receipt.json'),'proposed_limits':{'netconvert_starts':1,'technical_retry':0,'wallclock_s':30,'total_output_bytes':100000000,'SUMO':0,'TraCI':0,'GUI':0},'budget_basis':'One11-node/10-edge/14-external-lane network plus internals. Bound old compiled network is about15KB;100MB cap accommodates diagnostics without treating expected size as quota.30s is conservative engineering management ceiling, not measured candidate runtime. No repeat build is authorized by this draft.','preflight':['Explicit user approval bound to final request hash','All input,binary,schema hashes match','BUILD01 directory absent; no reuse or overwrite','Only netconvert process under exact argv, with process-local SUMO_HOME','Reserve one attempt before launch and preserve failed/partial outputs'],'termination':['Exit nonzero','Timeout30s','Output envelope100MB exceeded','Any diagnostic anomaly requires engineering review; no silent suppression or automatic retry'],'postbuild_gate':['No runtime release from process exit0 alone','Independent compiled geometry/requests/permission/domain/detector/path-storage review','Urban/TLS semantic invariants; three entry movements nonconflicting; aux0 outgoing0','Aux usable length[280,300]m and downstream>400m; no clipping','No manual compiled XML edits','Finalize additional endPos and all runtime hashes only after acceptance'],'monitoring_note':'Future watchdog uses polling/termination; cap is not OS hard quota, possible polling overshoot must be recorded. No executor is provided here.','project_cumulative_budget':{'status':'pending_parent_reconciliation_before_approval','known_stage6_old_SUMO':4,'known_stage6_old_netconvert':0,'new_P2_starts':0},'binding_manifest':bind(OUT/'input_manifest_revision03.json')}
save('SG6_BUILD_request_card_draft.json',build)
oldrec=ROOT/'data/processed/stage6_obstacle_20260913_v1/c04_launch_preparation_revision_03/attempts/S6_V1_C_S17_attempt1/execution_receipt.json'
rr=json.loads(oldrec.read_text());fp=Path(rr['output_bindings']['fcd.xml']['path']);assert bind(fp)['sha256']==rr['output_bindings']['fcd.xml']['sha256']
n=mx=0
with fp.open('rb') as f:
    for line in f:
        if b'<vehicle ' in line:n+=1;mx=max(mx,len(line))
jp=ROOT/'data/processed/stage6_obstacle_20260913_v1/c04_launch_preparation_revision_03/budget_journal/event_0011.json'
j=json.loads(jp.read_text());elapsed=next(a['wallclock_s'] for a in j['state']['attempts'] if a['attempt_id']=='S6_V1_C_S17_attempt1')
sample_ceiling=1858*2700;record_envelope=256;fcd_envelope=sample_ceiling*record_envelope
estimate={'historical_record_check':{'execution_receipt':bind(oldrec),'FCD':bind(fp),'vehicle_samples':n,'max_vehicle_record_bytes':mx,'budget_journal':bind(jp),'wallclock_s_C17':elapsed},'candidate_accounting':{'largest_planned_population':1858,'time_labels':2700,'crude_population_times_labels_ceiling':sample_ceiling,'planning_bytes_per_record':record_envelope,'FCD_planning_envelope_bytes':fcd_envelope,'note':'Overcounts population because scheduled entry is spread; conservative finite envelope.256bytes exceeds observed165; neither guarantees arbitrary diagnostic output size.'},'proposed_management_limits':{'SUMO_per_attempt_wallclock_s':180,'SUMO_total_wallclock_s':1080,'per_attempt_archive_bytes':1500000000,'total_archive_bytes':9000000000},'wallclock_basis':f'Historical{n}samples took{elapsed:.6f}s; scaling crudely to{sample_ceiling}samples gives{elapsed*sample_ceiling/n:.2f}s.180s ceiling includes >3x rough slack; nonlinear lane-change cost may invalidate estimate and triggers stop, not automatic extension.','disk_basis':'1.2842496GB FCD planning envelope plus about0.216GB allowance for other17-role files/logs. Watchdog required; abort and preserve if exceeded. This is new candidate budgeting, not inherited old2GB/120s allowance.','project_cumulative':'parent must reconcile all previous stages; this bounded estimate does not claim complete project cumulative usage'}
save('candidate_resource_estimate.json',estimate)
attempts=[]
for a in m['attempts']:
    ad=Path(a['output_root']).parent
    attempts.append({'attempt_id':a['attempt_id'],'logical_run_id':a['logical_run_id'],'role':a['role'],'arm':a['arm'],'seed':a['seed'],'argv':[env['binary']['sumo']['path'],'-c',str(ad/'scenario.final.sumocfg')],'cwd':str(ROOT),'input_source_bindings':a['input_files'],'final_config':{'path':str(ad/'scenario.final.sumocfg'),'sha256':None,'state':'pending_build_acceptance_and_materialization'},'output_root':a['output_root'],'network':a['network'],'status':'not_started_not_authorized'})
launch={'schema_version':1,'kind':'SG6_LAUNCH_REQUEST_DRAFT','status':'BLOCKED_PENDING_BUILD_AND_EXACT_INPUTS','launch_eligible':False,'approved':False,'authorized_starts':dict(SUMO=0,netconvert=0,TraCI=0,GUI=0),'binary':env['binary']['sumo'],'environment_overrides':{'SUMO_HOME':env['SUMO_HOME']},'attempts':attempts,'planned_attempt_order':[a['attempt_id'] for a in attempts],'proposed_limits':{'SUMO_total_starts':6,'smoke_starts':1,'validation_starts':4,'global_transient_technical_retry':1,**estimate['proposed_management_limits'],'netconvert_starts':0,'TraCI_starts':0,'GUI_starts':0},'gate_sequence':['Onefull2700s R720/17 smoke after exact card approval','Independent technical smoke acceptance; no scientific screening','R0/17 then R720/17; pause independent data/scientific review','ContinueR0/23 thenR720/23 regardless valid direction unless registered evidence/physical stop','Final vector only; no automatic obstacle closure'],'retry_expansion':'pending deterministic unique attempt2 inputs/hashes for any one failed attempt; must close before approval; globalone cannot expand scientific matrix','failure_rules':{'transient_process_environment':'may use same-parameter sharedretry ifpreapproved','route_config_design_error':'stop_revisedcard_required','collision_teleport':'complete_evidence_but_comparison_unsuitable_physical_event_stop_no_retry','source_observation_missing':'evidence_incomplete_stop','emergency_braking_only':'record_not_automatic_stop','negative_unidentified_U_NA_queue':'retain_continue_no_retry'},'blocking_fields':['approved_and_accepted_compiled_network','numeric_ramp_storage_endPos','17-role_live_mapper_and_full_pipeline_offline_review','all_final_input_hashes','deterministic_retry_expansion','watchdog_journal_recovery_executor_test_evidence','project_cumulative_budget','explicit_user_approval'], 'resource_estimate':bind(OUT/'candidate_resource_estimate.json'),'input_manifest':bind(OUT/'input_manifest_revision03.json'),'no_executor_implemented':True}
save('SG6_LAUNCH_request_card_draft.json',launch)
save('context_preflight_and_handoff.json',{'context_read':['AGENTS.md','docs/PROJECT_STATE.md','docs/DECISIONS.md','docs/EXPERIMENT_PROTOCOL.md','docs/WORKLOG.md','docs/STAGE6_P1_CANDIDATE_DESIGN_AND_REGISTRATION.md','docs/STAGE6_ASTRA_REASSESSMENT_AND_RECOVERY_PLAN.md',str(ROOT/'data/processed/stage6_obstacle_20260913_v1/recovery_candidate_design_revision_01/data/measurement_contract_revision04.md')],'protocol':'empty_known_not_frozen;exploratory_only','authorization':m['source_bindings'][0],'scope':'P2 isolated offline input implementation+validation+disabled request cards; no binaries','latest_input_manifest':'input_manifest_revision03.json','prior_revisions_retained':True,'performed':['5network plain/config inputs','5attempt demand and disabled config templates','17output roles and plannedidentity contracts','binary/plist and23local XSD dependencies bound','root tag defect repaired inrev02','undeparted output-only source added inrev03','178offlinechecks,15completeXMLschemaPASS,5unfinishedtemplatesexpectedREJECT,5negativefixtures','disabled exact-argv builddraft and blocked launchdraft'], 'remaining':['parent project cumulative budget reconciliation','independent input and scientific review','SG6-BUILD approval before any netconvert','build acceptance and numeric endPos','P2measurement adapter independent fullpipeline checks','final runtime inputs/retry and executor evidence','exactlaunchcard approval beforeSUMO'],'simulation_calls':dict(SUMO=0,netconvert=0,TraCI=0,GUI=0),'docs_changed':False})
save('engineering_P2_delivery_manifest.json',{'files':[bind(p) for p in sorted(OUT.rglob('*')) if p.is_file()]})
print('PASS: proposed BUILD1/30s/100MB; launch draft6/180s/1.5GB per attempt, all disabled.')
