import json
from pathlib import Path
import runtime_executor as e
B=Path(__file__).resolve().parent;P=B.with_name('runtime_validation_revision02');E=B.parent
old=json.loads((P/'RUNTIME_VALIDATION_CARD.json').read_text());m=json.loads((B/'runtime_input_manifest.json').read_text());history=json.loads((B/'prior_attempt_ledger.json').read_text())
def write(n,x):e.durable(B/n,x)
g=json.loads((P/'gate_contract.json').read_text());g['allowed_physical_status']+=['partial_evidence_physical','not_evaluable'];g['allowed_check_status']=['PASS','FAIL','NOT_COMPLETE','NOT_EVALUABLE'];g['failure_rule']='partial_evidence_physical and not_evaluable always progression_allowed=false; execution_complete_2700 is FAIL/NOT_COMPLETE for partial run; only exact twelve PASS+suitable may progress';g['physical_event_evidence_fields']=['event_type','observer','observed_excerpt','source_path','observed_unix'];write('gate_contract.json',g)
resource={'status':'Proposed_bounded_operational_ceiling_under_renewed_smoke_repair_authorization','limits':e.LIMITS,'monitoring_semantics':'polling_50ms_possible_overshoot_preserved','maximum_overshoot_bytes':'unknown; not hard quota','prior_consumption':e.binding(B/'prior_attempt_ledger.json'),'prior_SUMO_starts':1,'new_SUMO_starts_max':3,'cumulative_SUMO_starts_max':4,'new_monitored_seconds':540,'new_observed_bytes':4500000000,'estimation_basis':old['resource_budget'],'note':'same per-run180s/1.5GB bound derived from registered1858population2700labels; includes old9.373882084000797s/23552bytes; no doubling original unused slots'};write('resource_budget.json',resource)
card=dict(old);card.update(revision=3,attempts=m['attempts'],limits=e.LIMITS,executor=e.binding(B/'runtime_executor.py'),contract=e.binding(B/'RUNTIME_CONTRACT.md'),test_receipt=e.binding(B/'executor_test_receipt.json'),static_receipt=e.binding(B/'static_validation_receipt_revision02.json'),gate_contract=e.binding(B/'gate_contract.json'),input_manifest=e.binding(B/'runtime_input_manifest.json'),resource_budget=e.binding(B/'resource_budget.json'),prior_attempt_ledger=e.binding(B/'prior_attempt_ledger.json'),approval_sidecar_path=str(B/'RUNTIME_user_approval.json'),supersedes_card=e.binding(P/'RUNTIME_VALIDATION_CARD.json'),gate_path_pattern=str(B/'gates/<attempt_id>.json'))
card['new_user_authorization_quote']='smoke排查原因然后继续尝试';card['cumulative_runtime_budget']={'prior_starts':1,'new_max_starts':3,'maximum_including_failed_smoke':4,'past_time_s':history['prior_SUMO_wallclock_s'],'past_bytes':history['prior_SUMO_directory_bytes'],'no_automatic_retry':True};card['physical_stop_request']['path_pattern']=str(B/'runs/<attempt_id>/physical_stop_request.json')
card['wrapper_argv_by_attempt']={a['attempt_id']:[str(e.ROOT/'.venv/bin/python'),str(B/'runtime_executor.py'),'--card',str(B/'RUNTIME_VALIDATION_CARD.json'),'--approval',str(B/'RUNTIME_user_approval.json'),'--attempt',a['attempt_id'],'--execute'] for a in card['attempts']}
write('RUNTIME_VALIDATION_CARD.json',card)
approval=json.loads((P/'RUNTIME_user_approval.template.json').read_text());approval.update(card_path=str(B/'RUNTIME_VALIDATION_CARD.json'),card_sha256=e.digest(B/'RUNTIME_VALIDATION_CARD.json'),user_approval_quote='smoke排查原因然后继续尝试');write('RUNTIME_user_approval.template.json',approval)
write('runtime_delivery_manifest.json',{'status':'ready_for_exact_static_review','files':[e.binding(p) for p in sorted(B.rglob('*')) if p.is_file() and '__pycache__' not in p.parts],'prior_runtime_delivery_manifest':e.binding(P/'runtime_delivery_manifest.json'),'prior_failed_attempt_ledger':e.binding(B/'prior_attempt_ledger.json'),'card_sha256':e.digest(B/'RUNTIME_VALIDATION_CARD.json'),'real_SUMO_starts_this_packaging':0,'real_netconvert_starts_this_packaging':0,'prior_runtime_SUMO_starts':1,'known_amendment':'prior45-check receipt supersedes earlier42-check input snapshot before logical_run_id synchronization; old check receipt retained; no demand/scientific input changed'})
print(json.dumps({'card':e.binding(B/'RUNTIME_VALIDATION_CARD.json'),'manifest':e.binding(B/'runtime_delivery_manifest.json')},indent=2))
